### PR TITLE
add lstu

### PR DESCRIPTION
**Pull request by Tealk**
add new service lstu
https://framagit.org/fiat-tux/hat-softwares/lstu

### CODE REVIEW

**Comment by tosterkamp** [comment]
Exist other public servers with Istu except https://anzah.co ? If the number is very small, it is not worth maintaining the list.

**Comment by Tealk** [comment]
Sure, I can look for a few more but I don't feel comfortable adding instances to a list that aren't mine.

I have added the service because there is no list yet ;)

**Comment by Tealk** [comment]
would it be bad for you if the software is not the same @tosterkamp ?
then we rename it to urlshort 
i know instances with different software but the same function

**Comment by tosterkamp** [comment]
urlshort a good idea

**Comment by Tealk** [comment]
so I think now it should suit

**Comment by tosterkamp** [comment]
OK thank you. I will look at the pull requests the next days more closely.

I always sort the lists alphabetically, so that you can see more quickly whether an entry already exists. Maybe you can do the same next time.

**Comment by Tealk** [comment]
> I always sort the lists alphabetically

done with all ;)

**Pull request merged**
